services:
  rate-limiter-example:
    container_name: rate-limiter-example
    build:
      dockerfile: Dockerfile
    image: rate-limiter-example
    depends_on:
      - rate-limiter-redis
    networks:
      - default
    ports:
      - "8080:8080"

  rate-limiter-redis:
    container_name: rate-limiter-redis
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"
