spring.application.name=ip-rate-limiter

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:host.docker.internal}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

rate-limiter.script-path=rate_limit_script.lua
rate-limiter.type=default
